//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityCompra
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras_pend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compras_pend()
        {
            this.compras_pend_detalle = new HashSet<compras_pend_detalle>();
        }
    
        public int id { get; set; }
        public string auto_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string entidad_cirif { get; set; }
        public string entidad_nombre { get; set; }
        public string documento_tipo { get; set; }
        public decimal documento_monto { get; set; }
        public decimal documento_monto_divisa { get; set; }
        public int documento_items { get; set; }
        public decimal documento_factor_cambio { get; set; }
        public string documento_nombre { get; set; }
        public string usuario_nombre { get; set; }
        public string documento_numero { get; set; }
        public string documento_control { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras_pend_detalle> compras_pend_detalle { get; set; }
    }
}
