//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public long id { get; set; }
        public string nombreRazonSocial { get; set; }
        public string cirif { get; set; }
        public string dirFiscal { get; set; }
        public string telefono { get; set; }
    }
}
