//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long id { get; set; }
        public string autoPrd { get; set; }
        public string nombrePrd { get; set; }
        public decimal cantidad { get; set; }
        public decimal tasaIva { get; set; }
        public decimal precioNeto { get; set; }
        public long esPesado { get; set; }
        public string tipoIva { get; set; }
        public decimal costoUnd { get; set; }
        public decimal costoPromUnd { get; set; }
        public string autoDepartamento { get; set; }
        public string autoGrupo { get; set; }
        public string autoSubGrupo { get; set; }
        public string autoTasa { get; set; }
        public string categoria { get; set; }
        public string codigoProducto { get; set; }
        public string decimales { get; set; }
        public long diasEmpaqueGarantia { get; set; }
        public string empaqueCodigo { get; set; }
        public string empaqueDescripcion { get; set; }
        public long empaqueContenido { get; set; }
        public string tarifaPrecio { get; set; }
        public decimal precioSugerido { get; set; }
        public long idPendiente { get; set; }
        public decimal costoCompra { get; set; }
        public decimal costoPromedio { get; set; }
    }
}
