//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jornada
    {
        public long id { get; set; }
        public string fechaApertura { get; set; }
        public string horaApertura { get; set; }
        public string estatus { get; set; }
        public string fechaCierre { get; set; }
        public string horaCierre { get; set; }
        public string estatusTransmitida { get; set; }
    }
}
