//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperadorCierre
    {
        public long id { get; set; }
        public long idOperador { get; set; }
        public decimal diferencia { get; set; }
        public decimal efectivo { get; set; }
        public decimal divisa { get; set; }
        public decimal tarjeta { get; set; }
        public decimal otros { get; set; }
        public decimal devolucion { get; set; }
        public decimal subTotal { get; set; }
        public decimal total { get; set; }
        public decimal mEfectivo { get; set; }
        public decimal mDivisa { get; set; }
        public decimal mTarjeta { get; set; }
        public decimal mOtros { get; set; }
        public decimal mSubTotal { get; set; }
        public decimal mTotal { get; set; }
        public decimal firma { get; set; }
        public decimal mFirma { get; set; }
        public decimal cntDivisa { get; set; }
        public decimal mCntDivisa { get; set; }
    }
}
