//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string auto { get; set; }
        public string codigoPrd { get; set; }
        public string nombrePrd { get; set; }
        public long isActivo { get; set; }
        public string plu { get; set; }
        public string descripcionPrd { get; set; }
        public string referencia { get; set; }
        public string categoria { get; set; }
        public string codDepartamento { get; set; }
        public string departamento { get; set; }
        public string codGrupo { get; set; }
        public string grupo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string pasilo { get; set; }
        public long isPesado { get; set; }
        public long isOferta { get; set; }
        public long isDivisa { get; set; }
        public decimal tasaImpuesto { get; set; }
        public string ofertaDesde { get; set; }
        public string ofertaHasta { get; set; }
        public decimal ofertaprecio { get; set; }
        public decimal precio_1 { get; set; }
        public decimal precio_2 { get; set; }
        public decimal precio_3 { get; set; }
        public decimal precio_4 { get; set; }
        public long cont_1 { get; set; }
        public long cont_2 { get; set; }
        public long cont_3 { get; set; }
        public long cont_4 { get; set; }
        public string dec_1 { get; set; }
        public string dec_2 { get; set; }
        public string dec_3 { get; set; }
        public string dec_4 { get; set; }
        public string emp_1 { get; set; }
        public string emp_2 { get; set; }
        public string emp_3 { get; set; }
        public string emp_4 { get; set; }
        public long dias_Empaque_Garantia { get; set; }
        public decimal costo { get; set; }
        public decimal costoPromedio { get; set; }
        public decimal costoUnidad { get; set; }
        public decimal costoPromedioUnidad { get; set; }
        public string autoDepartamento { get; set; }
        public string autoGrupo { get; set; }
        public string autoMarca { get; set; }
        public string autoSubGrupo { get; set; }
        public string autoTasaIva { get; set; }
        public decimal precio_5 { get; set; }
        public long cont_5 { get; set; }
        public string dec_5 { get; set; }
        public string emp_5 { get; set; }
        public Nullable<decimal> precioMay_1 { get; set; }
        public Nullable<decimal> precioMay_2 { get; set; }
        public Nullable<long> contMay_1 { get; set; }
        public Nullable<long> contMay_2 { get; set; }
        public string empMay_1 { get; set; }
        public string empMay_2 { get; set; }
        public string decMay_1 { get; set; }
        public string decMay_2 { get; set; }
    }
}
