//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public string auto { get; set; }
        public string serie1 { get; set; }
        public string control { get; set; }
    }
}
