//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistema
    {
        public string auto { get; set; }
        public decimal factorCambio { get; set; }
        public string sucursalCodigo { get; set; }
        public string serieFactura { get; set; }
        public string serieNotaCredito { get; set; }
        public string serieNotaDebito { get; set; }
        public string activarRepesaje { get; set; }
        public decimal limiteRepesajeInferior { get; set; }
        public decimal limiteRepesajeSuperior { get; set; }
        public string modoOperacion { get; set; }
        public string activarBusquedaPorDescripcion { get; set; }
        public string autoDeposito { get; set; }
        public string autoVendedor { get; set; }
        public string autoCobrador { get; set; }
        public string autoTransporte { get; set; }
        public string autoMedioPagoEfectivo { get; set; }
        public string autoMedioPagoDivisa { get; set; }
        public string autoMedioPagoElectronico { get; set; }
        public string autoMedioPagoOtro { get; set; }
        public string clave1 { get; set; }
        public string clave2 { get; set; }
        public string clave3 { get; set; }
        public long clavePos { get; set; }
        public string tarifaAsignada { get; set; }
        public string EtiquetarPrecioPorTipoNegocio { get; set; }
        public string serieNotaEntrega { get; set; }
        public string equipoNumero { get; set; }
        public string autoConceptoMovVenta { get; set; }
        public string autoConceptoMovDevVenta { get; set; }
        public string autoConceptoMovSalida { get; set; }
        public string fechaUltActualizacion { get; set; }
    }
}
