//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPermiso
    {
        public string codigoGrupo { get; set; }
        public string codigoFuncion { get; set; }
        public long esActivo { get; set; }
        public long requiereClave { get; set; }
    }
}
