//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntitySqLitePosOffLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGrupo
    {
        public string autoUsuario { get; set; }
        public string autoGrupo { get; set; }
        public string usuarioCodigo { get; set; }
        public string usuarioDescripcion { get; set; }
        public string usuarioClave { get; set; }
        public string grupoDescripcion { get; set; }
        public string usuarioEstatus { get; set; }
    }
}
