//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_documentos
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_documento { get; set; }
        public string documento { get; set; }
        public decimal importe { get; set; }
        public string operacion { get; set; }
        public string auto_cxc { get; set; }
        public string auto_cxc_pago { get; set; }
        public string auto_cxc_recibo { get; set; }
        public string numero_recibo { get; set; }
        public System.DateTime fecha_recepcion { get; set; }
        public int dias { get; set; }
        public decimal castigop { get; set; }
        public decimal comisionp { get; set; }
    
        public virtual cxc cxc { get; set; }
        public virtual cxc cxc1 { get; set; }
        public virtual cxc_recibos cxc_recibos { get; set; }
    }
}
