//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEntityVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_agencias
    {
        public empresa_agencias()
        {
            this.clientes = new HashSet<clientes>();
            this.cxc = new HashSet<cxc>();
        }
    
        public string auto { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual ICollection<cxc> cxc { get; set; }
    }
}
